services:
  shoppingcart_service:
    container_name: shoppingcart_service
    networks:
      - cqrs-net
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=shoppingcartdb'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    ports:
      - '27017'
  mongo_express:
    depends_on:
      - shoppingcart_service
    image: 'mongo-express:latest'
    container_name: mongo_express
    networks:
      - cqrs-net
    environment:
      - 'ME_CONFIG_BASICAUTH_USERNAME=admin'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=admin'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=password'
      - 'ME_CONFIG_MONGODB_URL=mongodb://shoppingcart_service:27017'
      - 'ME_CONFIG_MONGODB_ENABLE_ADMIN=true'
      - 'ME_CONFIG_MONGODB_SERVER=shoppingcart_service'
    ports:
      - '8081:8081'

networks:
  cqrs-net:
    external: true
