volumes:
  MONGODB: {}

services:
  mongodb-service:
    image: 'mongo:latest'
    container_name: mongodb-service
    networks:
      - cqrs-net
    environment:
      - 'MONGO_INITDB_DATABASE=shoppingcartdb'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    volumes:
      - MONGODB:/data/db
    ports:
      - '27017:27017'
  mongo-express:
    image: 'mongo-express:latest'
    container_name: mongo-express
    networks:
      - cqrs-net
    depends_on:
      - mongodb-service
    environment:
      - 'ME_CONFIG_BASICAUTH_USERNAME=admin'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=admin'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=password'
      - 'ME_CONFIG_MONGODB_URL=mongodb://mongodb-service:27017'
      - 'ME_CONFIG_MONGODB_ENABLE_ADMIN=true'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb-service'
    ports:
      - '9081:8081'

networks:
  cqrs-net:
    external: true